import type { Metadata } from "next";
import { ReactNode } from "react";
import { defaultTheme, ThemeProvider } from "@/components/ThemeProvider";
import "../styles/index.scss";
import { boogaloo, montserrat } from "@/app/fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="ru" suppressHydrationWarning>
            <body
                className={`${montserrat.variable} ${boogaloo.variable}`}
                suppressHydrationWarning
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme={defaultTheme}
                    enableSystem
                    disableTransitionOnChange
                >
                    {/*<Preloader />*/}
                    <main suppressHydrationWarning className="main">
                        {children}
                    </main>
                    <script src="three.r119.min.js"></script>
                </ThemeProvider>
            </body>
        </html>
    );
}
