import type { Metadata } from "next";
import { ReactNode } from "react";
import { defaultTheme, ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="ru" suppressHydrationWarning>
            <body suppressHydrationWarning>
                <ThemeProvider
                    attribute="class"
                    defaultTheme={defaultTheme}
                    enableSystem
                    disableTransitionOnChange
                >
                    <main suppressHydrationWarning>{children}</main>
                </ThemeProvider>
            </body>
        </html>
    );
}
